version: 0.2

env:
  variables:
    CDN_NAME: web-community-cdn
    ACCOUNT_STACK_NAME: web-community-cdn-account
    CONFIG_REPO: byuweb/web-cdn
    EXTRA_TAGS: "data-sensitivity=public team=\"BYU Web Community\" if-questions-contact=\"Joseph Moore + James Spiers + Katria Lesser\""

phases:
  install:
    commands:
      - chmod a+x .codebuild/setup.sh && .codebuild/setup.sh
      - pip install awscli --upgrade --user
      - mkdir -p /root/.cache/yarn && yarn config set cache-folder /root/.cache/yarn
  pre_build:
    commands:
      - lerna bootstrap
      - lerna exec -- chmod a+x ./codebuild.sh
      - chmod a+x infrastructure/deploy-environment.sh
  build:
    commands:
      - lerna exec -- ./codebuild.sh
      - echo $EXTRA_TAGS
      - infrastructure/deploy-environment.sh $CDN_NAME $ENV $ROOT_DNS $ACCOUNT_STACK_NAME $CERTIFICATE_ARN $CONFIG_REPO $CONFIG_BRANCH "$EXTRA_TAGS"


cache:
  paths:
    - /var/cache/apt/**/*
    - /root/.cache/**/*
