version: 0.2

phases:
  build:
    commands:
      - echo Slack Webhook URL $SLACK_WEBHOOK_URL
      - echo Slack Channel $SLACK_CHANNEL
      - >-
        cdn-assembler
        --config main-config.yml
        --bucket $DESTINATION_S3_BUCKET
        --env $BUILD_ENV
        --verbose
        --cdn-host $CDN_HOST
        --slack-url $SLACK_WEBHOOK_URL
        --slack-channel $SLACK_CHANNEL

